### ISSUE TITLE
iOS does not render styles correctly

### ISSUE THREAD

**Issue by as-com** [JonHMChan/descartes#34]
![img_0647](https://cloud.githubusercontent.com/assets/3819625/13231864/1ee1f38a-d97a-11e5-8d54-9b6603d1787d.PNG)

This happens to me on iOS 8.

Error in console:
```
TypeError: undefined is not a function (evaluating 'Object.assign')
rowplato.js:43
(anonymous function)styles.js:1:588
```

**Comment by JonHMChan** [comment]
@as-com will look into it.

**Comment by JonHMChan** [comment]
This looks like it's been fixed.
