### ISSUE TITLE
Hard to remember name

### ISSUE THREAD

**Issue by wildfiremedia** [JonHMChan/descartes#37]
It took me days to find your site and I couldn't find it anywhere on Google search with lot of combination of "Javascript" and "CSS". On the last resort, I found HNAPP site that manage to find and I stil can't remember the name easily.
http://hnapp.com/?q=score%3E50%20css%20javascript

For the sake of getting enough exposure without difficulty to recall the name and pronunciation. You might want to change https://descartes.io to Carter or anything that is meaningful.

**Comment by SimonDever** [comment]
I think Descartes is actually a better name, especially if people have never heard of the man before. Did it not pique your curiosity? Day-kart is how it is pronounced, you can hear it on [YouTube](https://www.youtube.com/watch?v=K9qK7qNgXS8). I do, however, agree the website needs a keywords meta tag.

**Comment by JonHMChan** [comment]
Not going to change the name. Though it could be better, it's recognizable enough.
